[project]
name = "sift"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lark>=1.2.2",
    "ruff>=0.8.4",
]
[tool.ruff]
line-length = 88
select = ["E", "F", "W", "C90"]
ignore = ["E501", "W503"]
target-version = "py39"